package ar.edu.uade.example.digidex.viewmodel

val digimonNameOverrides = mapOf(
    "Yokomon" to "Pyocomon",
    "Motimon" to "Mochimon",
    "Frigimon" to "Yukidarumon",
    "Piximon" to "Piccolomon",
    "Datamon" to "Nanomon",
    "DemiDevimon" to "Pico Devimon",
    "Myotismon" to "Vamdemon",
    "Pabumon" to "Bubbmon",
    "ShogunGekomon" to "Tonosama Gekomon",
    "Gatomon" to "Tailmon",
    "Mammothmon" to "Mammon",
    "SkullMeramon" to "Death Meramon",
    "Pumpkinmon" to "Pumpmon",
    "Lillymon" to "Lilimon",
    "Phantomon" to "Fantomon",
    "MegaKabuterimon" to "Atlur Kabuterimon (Blue)",
    "MagnaAngemon" to "Holy Angemon",
    "VenomMyotismon" to "Venom Vamdemon",
    "Salamon" to "Plotmon",
    "Chuumon" to "Tyumon",
    "Machinedramon" to "Mugendramon",
    "Piedmon" to "Piemon",
    "Puppetmon" to "Pinochimon",
    "Scorpiomon" to "Anomalocarimon",
    "Divermon" to "Hangyomon",
    "Mushroomon" to "Mushmon",
    "Deramon" to "Delumon",
    "Cherrymon" to "Jyureimon",
    "Garbagemon" to "Garbemon",
    "Vilemon" to "Evilmon",
    "Candlemon" to "Candmon",
    "Revolvermon" to "Revolmon",
    "Magnadramon" to "Holydramon",
    "Gorillamon" to "Gorimon",
    "Veedramon" to "V-dramon",
    "Phoenixmon" to "Hououmon",
    "Penguienmon" to "Penmon",
    "SnowAgumon" to "YukiAgumon",
    "Meteormon" to "Insekimon",
    "Piddomon" to "Pidmon",
    "Chibomon" to "Chicomon",
    "DemiVeemon" to "Chibimon",
    "Raidramon" to "Lighdramon",
    "ExVeemon" to "XV-mon",
    "Imperialdramon" to "Imperialdramon(Dragon Mode)",
    "Azulongmon" to "Qinglongmon",
    "Omnimon" to "Omegamon"
)
